### ISSUE TITLE
Installation failed on LDPlayer 32-bit (Android 7.1.2).

### ISSUE THREAD

**Issue by i1itione** [HuskyDG/magisk-files#1]
Here is log:

- Device platform: x86
- Installing: 135ad27-delta (25101)
- Remount system partition as read-write
- Copy files to system partition
cat: can't open '/data/user_de/0/io.github.huskydg.magisk/install/magisk64': No such file or directory
! Installation failed

**Comment by HuskyDG** [comment]
Will release a fix soon

**Comment by HuskyDG** [comment]
Fixed in https://github.com/HuskyDG/magisk-files/tree/7325b001b32ed6ae0c805e0faba1e1d0b5d23719
