### ISSUE TITLE
any plans for collaborations with Lygisk?

### ISSUE THREAD

**Issue by pixincreate** [HuskyDG/magisk-files#10]
Having 3 Magisks that offer different functionalities apart from basic root access feels a bit too much for any user to begin with. 
magisk-files in collaboration with Lygisk would be better IMO as both give some more functionalities apart from Official Magisk.

**Comment by HuskyDG** [comment]
Hi @pixincreate, I planned to add it

**Comment by pixincreate** [comment]
Glad to hear

**Comment by HuskyDG** [comment]
Added in latest Canary version of Magisk Delta
