### ISSUE TITLE
Unable to add new apps to superuser access

### ISSUE THREAD

**Issue by DKluci** [HuskyDG/magisk-files#108]
![InShot_20240204_102416416](https://github.com/HuskyDG/magisk-files/assets/158796153/40aa81d1-e5ec-4b50-ab0b-ebb14366ae50)

![Screenshot_20240204_102630](https://github.com/HuskyDG/magisk-files/assets/158796153/90beb6dc-accd-4f06-9f99-8c677d9a9482)

I'm on latest kitsune 26404 version. Apps that I've added with superuser access before upgrading are working OK. But granting access to any new apps is not working. Added a GIF with Termux as example. 

If I let the access get denied, it shows up in Superuser tab under magisk, but is greyed out and using toggle button or revoke button force closes magisk.

Can you please help? Please let me know if I'm doing something wrong here

**Comment by DKluci** [comment]
By apps added before I mean apps added before upgrade to latest version are working fine

**Comment by DKluci** [comment]
[boot-2024-02-04-19-15-57.log](https://github.com/HuskyDG/magisk-files/files/14156977/boot-2024-02-04-19-15-57.log)

Here's the boot log. Reproduced issue after 19:11

**Comment by privacyportalUK** [comment]
yup same

**Comment by The1Naturat** [comment]
When magiskhide is enabled, root is not granted to any application (even the one I granted permissions to earlier). When I turn off mahiskhide, everything works as it should, but unfortunately I cannot log in to some applications (online banking, for example). R65C33E4F-kitsune (27001)

**Comment by DKluci** [comment]
I have updated to kitsune 27001 version, but issue still persists
![Screenshot_20240210_145154](https://github.com/HuskyDG/magisk-files/assets/158796153/19d116e8-879e-48b0-8b6f-da4cec5bae57)

**Comment by Morset1** [comment]
Same here
apps before update from v26400 is working, but any new request is rejected on v27001

**Comment by Morset1** [comment]
> Same here apps before update from v26400 is working, but any new request is rejected on v27001

I just tried denying root, the app showed in superuser list, but the moment i try to enable root check mark magisk suddenly close!

**Comment by The1Naturat** [comment]
> Did you use "User Authentication"?

When I click on this option magisk suddenly close.

**Comment by Morset1** [comment]
> Did you use "User Authentication"?
I think i got it fixed for me
 "User Authentication" option in R65C33E4F crash kitsune mask
I reverted to R65C0CF63 build and kitsune still reject root, but "User Authentication" option worked
So i set it to magisk provide and now root works for new apps.
I dunno if this matters, but i disabled "User Authentication" again and root is still working for new apps.

**Comment by DKluci** [comment]
> Did you use "User Authentication"?

Magisk is force closing when I click on User Authentication in Settings

**Comment by DKluci** [comment]
I installed stable 26.4 version and the issue got fixed. After updating again to latest canary build(27001), user authentication and superuser access toggles continue to work now. Not sure how, but this is fixed.
