### ISSUE TITLE
Question for Magisk Delta

### ISSUE THREAD

**Issue by skelletR** [HuskyDG/magisk-files#111]
@HuskyDG. I have Xiaomi Poco X3 NFC android 10, with Magisk 23 with riru and safetynet fix, now i want to move on, but the new magisk 26 i don't know about zygisk and shamiko things, i want to try your magisk Delta with new magiskhide and riru, of course is better than the old Magisk 23 i have it now, but i want the magisk Delta latest stable, can't find it

**Comment by HarriBuh** [comment]
There is no stable release of Magisk Delta. It's "canary" only and always will be, as far as I understood it.

**Comment by HarriBuh** [comment]
It's always the one at the top (you can also check the date of the update), so Yes.

**Comment by skelletR** [comment]
> It's always the one at the top (you can also check the date of the update), so Yes.

Thanks, just ask because in xda magisk Delta someone say have the version 25211 wnd I'm little confused
