### ISSUE TITLE
App failed to start after installation on Nox emulator

### ISSUE THREAD

**Issue by 0x1997** [HuskyDG/magisk-files#13]
I'm using Nox 6.6.1.2 / Android 5.1.1. I installed the d233698b-delta release and the app cannot be started after reboot.
Any thing I can do to help locate the issue? Thanks.

**Comment by HuskyDG** [comment]
No support for low Android version

**Comment by HuskyDG** [comment]
Hi @0x1997, I will consider to add support for it, but everything of Magisk will not work, only root access

**Comment by 0x1997** [comment]
Never mind.

**Comment by HuskyDG** [comment]
Support in the latest Canary version of Magisk Delta. Magisk modules is also working.
