### ISSUE TITLE
Boot Failure

### ISSUE THREAD

**Issue by IanWONeill** [HuskyDG/magisk-files#133]
Boot Failure after flashing init_boot.img using March update of A14

Device: Google Pixel 7
Android version: 14.0.0 (AP1A.240305.019.A1, Mar 2024)
Magisk version name: Kitsune Mask
Magisk version code: v26.4-kitsune-2

**Comment by clingerxiangdingdang** [comment]
android14很难刷吧，从来没有看见谁刷过

**Comment by IanWONeill** [comment]
You mean Kitsune does not support Android 14?

**Comment by xmdnx** [comment]
ig kitsune doesn't support AP1A rn

**Comment by IanWONeill** [comment]
> ig kitsune doesn't support AP1A rn

Update when?

**Comment by xmdnx** [comment]
@IanWONeill what? y u asking me
