### ISSUE TITLE
zygote does not work on Android 14

### ISSUE THREAD

**Issue by yusing** [HuskyDG/magisk-files#138]
Please update to magisk 27.0 to fix this issue, thanks

Device: TB138FC
Android version: 14
Magisk version name: 26.4-kitsune
Magisk version code: 26400

**Comment by xmdnx** [comment]
have this too, device just does not boot at all after enabling Zygisk

AP1A.240405.002
PixelOS_sweet-14.0-20240427-1952

**Comment by yusing** [comment]
> have this too, device just does not boot at all after enabling Zygisk
> 
> AP1A.240405.002
> PixelOS_sweet-14.0-20240427-1952

Mine worked after upgrading to 27.0-alpha, did u upgrade? Try patch and flash a stock image rather than direct install!
