### ISSUE TITLE
New app detects Magisk Delta 25.2 25200

### ISSUE THREAD

**Issue by DEVTE545** [HuskyDG/magisk-files#16]
Hello, I installed Magisk successfully and added zygisk lsposed, safetynet fix, etc., the play store does not detect root and all other apps, this app was not detecting Magisk Delta at first with only MagiskHaide, but a new update was added to the app and the root was detected then, I I tried using the Shamiko extension and renaming the Magic app didn't work either, I also used PrivacySpace that didn't work either, any other idea? Is there a stronger MagiskHide in the next versions?
i have android 11 ui 3.1 .
It is a special application for a telecom company, to buy the Internet, call credit, and control the SIM number
https://m.apkpure.com/mystc-ksa/com.stc

**Comment by HuskyDG** [comment]
![Screenshot_20220819-171125_mystc](https://user-images.githubusercontent.com/84650617/185597208-554b65fa-d479-4860-9cea-14a364f95e93.png)

**Comment by DEVTE545** [comment]
I figured out why, I disabled zygisk and it worked, looks like I'll switch to riru, Sorry to bother you
