### ISSUE TITLE
Logcat errors

### ISSUE THREAD

**Issue by firefinchdev** [HuskyDG/magisk-files#18]
I installed Magisk Delta, and observed that Android Studio is no longer able to detect `running debuggable apps`.
I cannot start the debugger because of the same (AS shows a list of apps, so user selects the app to attach debugger, but the list is empty).

Afaik android studio parses logcat output to detect list of running debuggable apps.

Following is a line from logs in android studio:
1. When using Magisk Delta 25.2:
```
2022-09-08 16:36:04.108 3367-3436/? I/okhttp.OkHttpClient: --> END GET
```
2. When using Magisk 25.2:
```
2022-09-08 16:36:04.108 3367-3436/com.softinit.proxytry I/okhttp.OkHttpClient: --> END GET
```
Notice that package names/application id is missing when using `Magisk Delta`.

Issue is resolved when I revert back to official Magisk 25.2

However, the only visible package name (in logs) are for the launcher app (`app.lawnchair`), and android studio detects it as debuggable app if its running, and atleast one log from this app is present in logs.

Besides Android Studio, this is also breaking some automation stuff, that relies on parsing logcat to get app id.

**Comment by HuskyDG** [comment]
Magisk Delta does not have v24.2, you mean v25.2?

**Comment by firefinchdev** [comment]
Yes sorry 25.2

**Comment by firefinchdev** [comment]
Hi,
Did you check?
I can help with logs, testing, etc.

**Comment by HuskyDG** [comment]
Can you check the latest debug of magisk delta? I have no idea why it cause this problem.

**Comment by firefinchdev** [comment]
Just tried, yes, working perfectly fine on debug.

Just to make sure that things were in fact breaking before..
I uninstalled debug, and reverted back to original Magisk, then flashed stable delta exactly the same way I installed debug delta, and problem was reproducable.

Now, again switched back to debug delta, and the problem is gone.
