### ISSUE TITLE
Does not work in memu emulator

### ISSUE THREAD

**Issue by huayuprophet** [HuskyDG/magisk-files#2]
Android 9 image

**Comment by HuskyDG** [comment]
Can you please describe the problem and attach installation logs, magisk logs or something?

**Comment by huayuprophet** [comment]
The  "Direct Install into system partition"  options are not displayed.
![image](https://user-images.githubusercontent.com/106079510/177724140-a57d117c-57ad-44a1-9a08-b141cf0b7c5f.png)

**Comment by huayuprophet** [comment]
![image](https://user-images.githubusercontent.com/106079510/177724527-0b33d4f1-4afe-406b-b9d7-97090bb77c22.png)
Choose the direct install option,it's will be fail.
sorry my english is not good

**Comment by HuskyDG** [comment]
@huayuprophet https://huskydg.github.io/magisk-files/app-release.apk

**Comment by huayuprophet** [comment]
oh,yes it is.
very thanks.

**Comment by huayuprophet** [comment]
wait。I use the Canary version, with the option to install to the system partition.
But it didn't work. magisk is n/v after reboot.
I think it's better to try by yourself。

**Comment by huayuprophet** [comment]
on memu emulator
