### ISSUE TITLE
Doesn't work on LDPlayer 9

### ISSUE THREAD

**Issue by mondis1337** [HuskyDG/magisk-files#2]
![image](https://user-images.githubusercontent.com/55624582/180314825-e9bdb71e-9128-47cc-888c-e88d9c460ac6.png)

log:
[magisk_log_2022-07-22T02.03.43.log](https://github.com/HuskyDG/magisk-files/files/9162765/magisk_log_2022-07-22T02.03.43.log)

**Comment by HuskyDG** [comment]
Can you send installation log?

**Comment by mondis1337** [comment]
> Can you send installation log?
already sent
[https://github.com/HuskyDG/magisk-files/files/9162765/magisk_log_2022-07-22T02.03.43.log](log)

**Comment by HuskyDG** [comment]
> > Can you send installation log?
> 
> already sent under the screenshot

Press the Save button, it will save the logs with error message

**Comment by HuskyDG** [comment]
> [magisk_install_log_2022-07-22T19.18.44.log](https://github.com/HuskyDG/magisk-files/files/9168427/magisk_install_log_2022-07-22T19.18.44.log)

No error messages 🤔🤔 If i have time I will take a look in LDPlayer

**Comment by PhurYO** [comment]
BUMPPP

**Comment by YaeSakuraQvQ** [comment]
doesn't work on LDPlayer 9,too,repair,plz
![1](https://user-images.githubusercontent.com/87939280/180801905-26b66319-46a3-4a99-a408-be0e033bc7ae.PNG)

here is the log
```
- Device platform: x86_64
- Installing: 25.2-delta (25200)
****************************
 Magisk Delta (System Mode) 
 by HuskyDG 
****************************
*******************
 Powered by Magisk 
*******************
- Remount system partition as read-write
! Installation failed
- Copy files to system partition
```
I also try your old tool "magisk-on-android-x86" doesn't work on ldplayer9,too

**Comment by YaeSakuraQvQ** [comment]
the result of the command
![image](https://user-images.githubusercontent.com/87939280/180909763-66d58a34-5bcb-466d-8deb-706551adc29c.png)
and I can write /system with mt
![image](https://user-images.githubusercontent.com/87939280/180910726-542eed36-e2e9-450c-8593-113b2b9662d7.png)

**Comment by HuskyDG** [comment]
Try [app-debug.zip](https://github.com/HuskyDG/magisk-files/files/9186885/app-debug.zip)

**Comment by mondis1337** [comment]
> Try [app-debug.zip](https://github.com/HuskyDG/magisk-files/files/9186885/app-debug.zip)

```
- Device platform: x86_64
- Installing: acdecf4e-delta (25201)
umount: can't unmount /dev/sysmount_mirror: No such file or directory
****************************
 Magisk Delta (System Mode) 
 by HuskyDG 
****************************
*******************
 Powered by Magisk 
*******************
- Remount system partition as read-write
- Copy files to system partition
- Patch sepolicy file
! Cannot find sepolicy file
! Installation failed
```

**Comment by HuskyDG** [comment]
> > Try [app-debug.zip](https://github.com/HuskyDG/magisk-files/files/9186885/app-debug.zip)
> 
> ```
> - Device platform: x86_64
> - Installing: acdecf4e-delta (25201)
> umount: can't unmount /dev/sysmount_mirror: No such file or directory
> ****************************
>  Magisk Delta (System Mode) 
>  by HuskyDG 
> ****************************
> *******************
>  Powered by Magisk 
> *******************
> - Remount system partition as read-write
> - Copy files to system partition
> - Patch sepolicy file
> ! Cannot find sepolicy file
> ! Installation failed
> ```

Oh I think rootfs should skip sepolicy patches, will give another build soon

**Comment by HuskyDG** [comment]
Try [app-debug.zip](https://github.com/HuskyDG/magisk-files/files/9187389/app-debug.zip)

**Comment by HuskyDG** [comment]
Oh my bad

**Comment by mondis1337** [comment]
> Try [app-debug.zip](https://github.com/HuskyDG/magisk-files/files/9187389/app-debug.zip)

Now this:
```
- Device platform: x86_64
- Installing: 450c4f6a-delta (25201)
****************************
 Magisk Delta (System Mode) 
 by HuskyDG 
****************************
*******************
 Powered by Magisk 
*******************
- Remount system partition as read-write
- Copy files to system partition
- Patch sepolicy file
! Cannot find sepolicy file
sh: can't create /dev/sysmount_mirror/system/etc/init/bootanim.rc: nonexistent directory
- Add init boot script
! Installation failed
```

**Comment by HuskyDG** [comment]
> > Try [app-debug.zip](https://github.com/HuskyDG/magisk-files/files/9187389/app-debug.zip)
> 
> Now this:
> 
> ```
> - Device platform: x86_64
> - Installing: 450c4f6a-delta (25201)
> ****************************
>  Magisk Delta (System Mode) 
>  by HuskyDG 
> ****************************
> *******************
>  Powered by Magisk 
> *******************
> - Remount system partition as read-write
> - Copy files to system partition
> - Patch sepolicy file
> ! Cannot find sepolicy file
> sh: can't create /dev/sysmount_mirror/system/etc/init/bootanim.rc: nonexistent directory
> - Add init boot script
> ! Installation failed
> ```

Can you send result after executing this command:
```
cat /proc/mounts >/sdcard/mounts.txt
```

**Comment by YaeSakuraQvQ** [comment]
the result
```
/dev/root / ext4 ro,seclabel,relatime,block_validity,delalloc,barrier,user_xattr 0 0
tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
none /dev/cpuctl cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0
proc /proc proc rw,relatime,gid=3009,hidepid=2 0 0
none /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
tmpfs /mnt tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
tmpfs /mnt tmpfs rw,seclabel,relatime,mode=755,gid=1000 0 0
Applications /mnt/shared/Applications vboxsf rw,nodev,relatime,ttl=0,iocharset=utf8,uid=1023,gid=1023,dmode=0777,fmode=0777 0 0
Pictures /mnt/shared/Pictures vboxsf rw,nodev,relatime,ttl=0,iocharset=utf8,uid=1023,gid=1023,dmode=0777,fmode=0777 0 0
Misc /mnt/shared/Misc vboxsf rw,nodev,relatime,ttl=0,iocharset=utf8,uid=1023,gid=1023,dmode=0777,fmode=0777 0 0
Bug /mnt/shared/Bug vboxsf rw,nodev,relatime,ttl=0,iocharset=utf8,uid=1023,gid=1023,dmode=0777,fmode=0777 0 0
/data/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal 0 0
/data/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal 0 0
/data/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal 0 0
none /acct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
none /config configfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/block/sdb1 /cache ext4 rw,seclabel,nosuid,nodev,noatime,errors=panic,data=ordered 0 0
/dev/block/sdb2 /data ext4 rw,seclabel,nosuid,nodev,noatime,errors=panic,data=ordered 0 0
/dev/block/sdc2 /data/media ext4 rw,seclabel,nosuid,nodev,noatime,data=ordered 0 0
tmpfs /storage tmpfs rw,seclabel,relatime,mode=755,gid=1000 0 0
/data/media /storage/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal 0 0
tmpfs /storage/self tmpfs rw,seclabel,relatime,mode=755,gid=1000 0 0
```

**Comment by mondis1337** [comment]
> > > Try [app-debug.zip](https://github.com/HuskyDG/magisk-files/files/9187389/app-debug.zip)
> > 
> > 
> > Now this:
> > ```
> > - Device platform: x86_64
> > - Installing: 450c4f6a-delta (25201)
> > ****************************
> >  Magisk Delta (System Mode) 
> >  by HuskyDG 
> > ****************************
> > *******************
> >  Powered by Magisk 
> > *******************
> > - Remount system partition as read-write
> > - Copy files to system partition
> > - Patch sepolicy file
> > ! Cannot find sepolicy file
> > sh: can't create /dev/sysmount_mirror/system/etc/init/bootanim.rc: nonexistent directory
> > - Add init boot script
> > ! Installation failed
> > ```
> 
> Can you send result after executing this command:
> 
> ```
> cat /proc/mounts >/sdcard/mounts.txt
> mountpoint -d / >/sdcard/mountpoint.txt
> ```

[mounts.txt](https://github.com/HuskyDG/magisk-files/files/9189865/mounts.txt)
[mountpoint.txt](https://github.com/HuskyDG/magisk-files/files/9189866/mountpoint.txt)

**Comment by HuskyDG** [comment]
Should be fixed
[app-debug.zip](https://github.com/HuskyDG/magisk-files/files/9189888/app-debug.zip)

**Comment by mondis1337** [comment]
Thank you for fixing. Everything works now

**Comment by httpsColon** [comment]
> Should be fixed [app-debug.zip](https://github.com/HuskyDG/magisk-files/files/9189888/app-debug.zip) ![Screenshot (189)](https://user-images.githubusercontent.com/84650617/181010570-2bc3bb91-dea6-4ee0-a8d3-7771bf9bafaf.png)

![image](https://user-images.githubusercontent.com/102579986/193096793-a1b494ae-9c21-48d9-9338-8da5e14127b8.png)

Should these two items be checked during installation?  for LDplayer

**Comment by ZTzTopia** [comment]
this problem appears again in the current version of ldplayer 😞

**Comment by Synzed** [comment]
this problem is still up2date, why is this closed :/
