### ISSUE TITLE
Zygisk Is Not Enabled Bug In A13

### ISSUE THREAD

**Issue by Kero309x** [HuskyDG/magisk-files#20]
Tested on Aosp 13 has many bugs, after flashing lsposed zygisk and enabling zygisk then restating your phone and checkout the Magisk modules it will say module is not enabled because of zygisk is not enabled...

Another bugs I faced with Magisk Delta in Screenshots after restarting my device
.
![Screenshot_20220924-145810_Magisk_Delta](https://user-images.githubusercontent.com/55901942/192100593-7cb0f5ed-0521-4385-a19b-0468587479d4.png)
![Screenshot_20220924-145817_Magisk_Delta](https://user-images.githubusercontent.com/55901942/192100598-f821e4cf-509e-4d0c-b4db-e415305d6589.png)
![Screenshot_20220924-150827_Settings](https://user-images.githubusercontent.com/55901942/192100602-a31d2dee-fd5d-4678-912c-8948b6674bb4.png)
![Screenshot_20220924-150843](https://user-images.githubusercontent.com/55901942/192100604-08ae9812-6614-4ecc-9203-5a6c4b21b552.png)
![Screenshot_20220924-150847_Magisk_Delta](https://user-images.githubusercontent.com/55901942/192100605-e5130a02-ac28-438e-8b98-7513f6ae04ef.png)

**Comment by HuskyDG** [comment]
https://github.com/HuskyDG/magisk-files#canary--debug

**Comment by JesusMaxim** [comment]
Universal Safetynet fix in Android 13 is not yet officially supported (there is a mod that is)
