### ISSUE TITLE
Google Pay (GPay) started seeing root

### ISSUE THREAD

**Issue by ZerkerEOD** [HuskyDG/magisk-files#206]
Not sure what happened, I havne't updated anything and my gpay was working yesterday, today gpay is detecting root.

Running on a Pixel 7 Pro running Android 14.

**Comment by adriantc** [comment]
Confirmed. I am on the same boat. Xiaomi Poco F2 Pro running Android 12, latest Magisk Delta version. Tried updating USNF to 2.4.0 MOD 2.0 (had 1.2 before), but doesn't seem to have made any difference.

**Comment by ZerkerEOD** [comment]
Update, looks like I also lost call screening

**Comment by adriantc** [comment]
Check the following thread for the fix: https://xdaforums.com/t/magisk-google-wallet-pay-with-magisk.4471279/page-12#posts

**Comment by ZerkerEOD** [comment]
@adriantc thanks that patch fixed it!

**Comment by andrevmatos** [comment]
If relevant for anyone: in my Derpfest 13 @ OnePlus 7T (hotdogb), installing the Play Integrity Fix 12.3 (tested with some previous versions too) on top of Magisk Delta Beta (26100) made the system unusable. Some interactions, even e.g. opening Settings, were extremely slow and often FCing.

Updating to Magisk Delta Canary (26301) and installing the latest module version again made it work for me, and device integrity is passing. Thanks!

**Comment by freebumba27** [comment]
> If relevant for anyone: in my Derpfest 13 @ OnePlus 7T (hotdogb), installing the Play Integrity Fix 12.3 (tested with some previous versions too) on top of Magisk Delta Beta (26100) made the system unusable. Some interactions, even e.g. opening Settings, were extremely slow and often FCing.
> 
> Updating to Magisk Delta Canary (26301) and installing the latest module version again made it work for me, and device integrity is passing. Thanks!

Could you please guide how you update to Magisk Delta Canary (26301) I have downloaded the release apk but directly installing to of Magisk Delta Beta (26100) does not work.
