### ISSUE TITLE
magiskhide

### ISSUE THREAD

**Issue by VaMPIRESqq** [HuskyDG/magisk-files#207]
if I add app to magiskhide, app always crasher

**Comment by DanGLES3** [comment]
> if I add app to magiskhide, app always crasher

That usually happens when you use a font module, if that's the case you'll need a module like this
https://github.com/HuskyDG/Zygisk-FontLoader

**Comment by VaMPIRESqq** [comment]
> > if I add app to magiskhide, app always crasher
> 
> That usually happens when you use a custom font module, if that's the case you'll need a module like this https://github.com/HuskyDG/Zygisk-FontLoader

thank you, it helped, but applications continue to crash, albeit with less efficiency

**Comment by VaMPIRESqq** [comment]
disappeared by itself with the update.

**Comment by VaMPIRESqq** [comment]
.

**Comment by VaMPIRESqq** [comment]
.
