### ISSUE TITLE
App Force Close with Magisk Hide

### ISSUE THREAD

**Issue by ele3131** [HuskyDG/magisk-files#21]
Using Magisk Hide with "Inter Bank" force close it when opening it:

https://play.google.com/store/apps/details?id=br.com.intermedium&hl=pt_BR&gl=US

When not using Magisk Hide everything works fine.

[logcat.txt](https://github.com/HuskyDG/magisk-files/files/9693321/logcat.txt)

**Comment by HuskyDG** [comment]
https://t.me/magiskdelta/325
