### ISSUE TITLE
Waydroid support

### ISSUE THREAD

**Issue by jhay06** [HuskyDG/magisk-files#26]
hi , i know this magisk delta can be install on emulator , and i try the option to install magisk module to /system partition only because im running on waydroid, but magisk delta removes only the current magisk installed ,  but the latest magsik v25 is not installed so i lost may magisk module only the magisk manager remains . 

maybe because the option is for emulator , waydroid is not emulator it is a container. so im hoping that we can install latest magisk using waydroid . im also looking for the patch file instead of flashing it using magisk manager . do you have the file ? 

thanks 

btw: im using waydroid on Ubuntu touch . (arm64)

**Comment by HuskyDG** [comment]
Waydroid is chroot system not emulator and will not be supported
