### ISSUE TITLE
Turn off LDPlayer 9.0.24 built-in root will break Magisk Delta (become not installed).

### ISSUE THREAD

**Issue by i1itione** [HuskyDG/magisk-files#29]
I think there is something breaks Magisk Delta when turning off LDPlayer 9.0.24 built-in root option.

Turn on then Magisk is installed.
![Screenshot_20221018-035140](https://user-images.githubusercontent.com/21694907/196270683-c51942a7-4502-4f40-835d-f42cf22be6d0.png)

Turn off then Magisk is not installed.
![Screenshot_20221018-035221](https://user-images.githubusercontent.com/21694907/196270706-204b9aaa-ceb4-4d04-b5be-49adc7c88450.png)

**Comment by dinatha08** [comment]
what 😭😭😭

**Comment by HuskyDG** [comment]
https://github.com/HuskyDG/magisk-files#how-to-install-magisk-into-emulator-such-as-noxplayer-ldplayer-etc

**Comment by HuskyDG** [comment]
~~Disable Root access in emulator settings~~ Some emulator deletes su binary after disabling root access, accidentally remove magisk's su so directly delete /system/xbin/su instead.

**Comment by i1itione** [comment]
> ~Disable Root access in emulator settings~ Some emulators delete su binary after disabling root access, accidentally remove magisk's su so directly delete /system/xbin/su instead.

Yes, it works, just delete /system/(x)bin/su and don't turn off root option in LDPlayer.
