### ISSUE TITLE
On memu emulator,zygisk doesn't work when it have enabled.

### ISSUE THREAD

**Issue by huayuprophet** [HuskyDG/magisk-files#3]
There is a strange result.
if used stable or canary release,it doesn't work to enable zygisk.And the WLAN will be failed at the same time,search no wifi.
![图片](https://user-images.githubusercontent.com/106079510/180630865-ec2dd5e3-78a2-4238-86ee-981e31363de5.png)
![图片](https://user-images.githubusercontent.com/106079510/180630870-a4f0c39c-631d-4baf-a298-55f4706d8329.png)

BUT strangely,when used debug release,it's working! And the wifi well too.
![图片](https://user-images.githubusercontent.com/106079510/180630933-cc5b4ce1-38a4-4384-8b1e-23e5bfad5f22.png)
![图片](https://user-images.githubusercontent.com/106079510/180630945-40e10e7d-234d-42b4-89d2-c502082074b5.png)
So i don't know how to save debug logs.I can't catch the failed logs with DEBUG release.

ENV: MEMU emulator,Android9 image

**Comment by PhurYO** [comment]
On NoxPlayer Also

**Comment by HuskyDG** [comment]
Magisk logs?

**Comment by HuskyDG** [comment]
Compared with official, Magisk Delta only provides the way to install without boot image and does not modify anything of Zygisk.

**Comment by lytruongduan2020** [comment]
You need to install new memu player and you will got problems

**Comment by HuskyDG** [comment]
No logs

**Comment by huayuprophet** [comment]
well,wait a moment

**Comment by huayuprophet** [comment]
There is logs on stable release. Zygisk is failed when enabled.
[magisk_log_2022-07-28T06.10.08.log](https://github.com/HuskyDG/magisk-files/files/9199786/magisk_log_2022-07-28T06.10.08.log)
![图片](https://user-images.githubusercontent.com/106079510/181269412-bf36219b-7f69-480f-8fea-a772f4f27d58.png)

There is logs on DEBUG release. Zygisk is successful.
[magisk_log_2022-07-27T22.18.26.log](https://github.com/HuskyDG/magisk-files/files/9199861/magisk_log_2022-07-27T22.18.26.log)
