### ISSUE TITLE
Screen is not turning on after forcing SU

### ISSUE THREAD

**Issue by ai212983** [HuskyDG/magisk-files#3]

**Comment by ai212983** [comment]
Just in case someone will run into the same problem:
1. Reboot into fastboot mode 
2. Reflash with stock boot.img
3. Reboot, install standard Magisk, patch boot.img
4. Reboot, open Magisk, choose "uninstall", this will remove root and all modules.
5. Reboot, install Magisk Delta, re-patch boot.img.
6. Reboot, all Magisk Delta settings (including SuList) will be reset
7. Install Magisk modules and re-add apps to SuList.

**Comment by ai212983** [comment]
After installing all my modules back (except Shamiko), all seems to work now. Probably it was a glitch or some kind of conflict.

**Comment by truly-irham** [comment]
Wow thanks for the heads up, I'm currently facing the exact same issue XD Now I'm trying to fix this issue. Will update later.
