### ISSUE TITLE
It seems that logcat based MagiskHide doesn't work on LDPlayer.

### ISSUE THREAD

**Issue by i1itione** [HuskyDG/magisk-files#30]
I tried both LDPlayer 4 (Android 7.1.2) and LDPlayer 9 (Android 9), MagiskHide doesn't work.

Picture 1: Magisk-delta is installed.
![Screenshot_20221020-055225](https://user-images.githubusercontent.com/21694907/196812883-19357bc6-563f-4d5c-8de2-6ee8613b51f8.png)

Picture 2: No apps already given root permission.
![Screenshot_20221020-055228](https://user-images.githubusercontent.com/21694907/196812888-6f9eb159-9a8d-4573-8ea0-89a987b31de0.png)

Picture 3: MagiskHide on.
![Screenshot_20221020-055242](https://user-images.githubusercontent.com/21694907/196812891-3442ee69-97ca-4151-abd1-31e8de8357dd.png)

Picture 4: For example, I select Terminal Emulator.
![Screenshot_20221020-055248](https://user-images.githubusercontent.com/21694907/196812893-c6961d1f-86d2-4425-962f-48b9abab71f3.png)

Picture 5: In Terminal Emulator, when I type su it is still showing superuser request.
![Screenshot_20221020-055258](https://user-images.githubusercontent.com/21694907/196812894-49f79570-7d27-417d-8837-e4e2530987e4.png)

**Comment by HuskyDG** [comment]
No log

**Comment by i1itione** [comment]
> No log

[magisk_log_2022-10-21T18.58.51.log](https://github.com/HuskyDG/magisk-files/files/9838375/magisk_log_2022-10-21T18.58.51.log)

I hope it might help.

**Comment by HuskyDG** [comment]
Expected because of no SeLinux, so some check in MagiskHide will fail

**Comment by HuskyDG** [comment]
Should work on f4732800-delta

**Comment by i1itione** [comment]
> Should work on f4732800-delta

It still doesn't work, maybe it is a problem of LDPlayer itself?
[magisk_log_2022-10-22T00.34.10.log](https://github.com/HuskyDG/magisk-files/files/9840863/magisk_log_2022-10-22T00.34.10.log)

**Comment by HuskyDG** [comment]
Type this command and open few apps in 20 second then send `logcat_test.txt` here

```
timeout 20 logcat -b events -s am_proc_start >/sdcard/logcat_test.txt
```

**Comment by i1itione** [comment]
> Type this command and open few apps in 20 second then send `logcat_test.txt` here
> 
> ```
> timeout 20 logcat -b events -s am_proc_start >/sdcard/logcat_test.txt
> ```

[logcat_test.txt](https://github.com/HuskyDG/magisk-files/files/9842457/logcat_test.txt)

Thanks a lot for your hard work.

**Comment by HuskyDG** [comment]
But... Why do you still want to use logcat MagiskHide instead of zygisk MagiskHide? 🤔

**Comment by HuskyDG** [comment]
LDPlayer Android 9 works

![Screenshot_20221022_125549](https://user-images.githubusercontent.com/84650617/197322956-53ddcac2-6d2e-4aaf-ba16-923f39ed1c00.png)

**Comment by i1itione** [comment]
> But... Why do you still want to use logcat MagiskHide instead of zygisk MagiskHide? 🤔

How to use Zygisk MagiskHide? Just enable the zygisk option? I don't even know this is possible, thank you.

**Comment by i1itione** [comment]
It works on LDPlayer 4 (Android 7.1.2), after I enabled Zygisk and MagiskHide.

10-22 18:20:23.928  3515  3515 I : zygisk32: [jackpal.androidterm] is on the hidelist
10-22 18:20:23.930  1120  2653 D : zygisk: cleanup mount namespace for pid=[3515]
10-22 18:20:23.931  3521  3521 D : hide_daemon: handling PID=[3515]
10-22 18:20:23.955  3521  3521 D : hide_daemon: Unmounted (/system/bin/app_process64)
10-22 18:20:23.969  3521  3521 D : hide_daemon: Unmounted (/system/bin/app_process32)
10-22 18:20:23.996  3521  3521 D : hide_daemon: Unmounted (/sbin)
