### ISSUE TITLE
this app can detect magiskhide please help

### ISSUE THREAD

**Issue by diedbug2002** [HuskyDG/magisk-files#32]
https://play.google.com/store/apps/details?id=com.esunbank

what information i need to provide further?

**Comment by HuskyDG** [comment]
Work with MagiskHide / MomoHide and disable USB debugging
Just do not enable Zygisk, this app can detect Zygisk even with Shamiko v0.5.2

**Comment by diedbug2002** [comment]
> Work with MagiskHide / MomoHide and disable USB debugging Just do not enable Zygisk, this app can detect Zygisk even with Shamiko v0.5.2

thx for quick reply ill try to find what happend

**Comment by diedbug2002** [comment]
hi just test again with a clean flashed ROM (Android 12)

it still detect root with following settings

![image](https://user-images.githubusercontent.com/25360103/197327254-2b394ccb-789c-40a7-b96f-e63c777235fc.png)

![image](https://user-images.githubusercontent.com/25360103/197327262-f2fa707c-c506-48f9-8a47-496b1c21adfe.png)

app shows root detected
![image](https://user-images.githubusercontent.com/25360103/197327282-92d786a4-02af-464b-88f3-4aecc7aa6b58.png)

app version
4.5.8

please help

previous verion hide work fine (4.5.7)
