### ISSUE TITLE
hi HuskyDG just test again with a clean flashed ROM (Android 12)

### ISSUE THREAD

**Issue by diedbug2002** [HuskyDG/magisk-files#33]
hi just test again with a clean flashed ROM (Android 12)

it still detect root with following settings

![image](https://user-images.githubusercontent.com/25360103/197327254-2b394ccb-789c-40a7-b96f-e63c777235fc.png)

![image](https://user-images.githubusercontent.com/25360103/197327262-f2fa707c-c506-48f9-8a47-496b1c21adfe.png)

app shows root detected
![image](https://user-images.githubusercontent.com/25360103/197327282-92d786a4-02af-464b-88f3-4aecc7aa6b58.png)

app version
4.5.8

please help

previous verion hide work fine (4.5.7)

_Originally posted by @diedbug2002 in https://github.com/HuskyDG/magisk-files/issues/32#issuecomment-1287665870_
      
magisk hide enable
![image](https://user-images.githubusercontent.com/25360103/197327578-8d4fb95e-6821-4139-ab7e-dff628b98e7c.png)

include this app
![image](https://user-images.githubusercontent.com/25360103/197327595-4109979a-53b4-42c2-bb0e-746f8329f00f.png)

**Comment by HuskyDG** [comment]
I'm using Android 12 and it works fine

**Comment by diedbug2002** [comment]
> I'm using Android 12 and it works fine

hmm so weird

**Comment by HuskyDG** [comment]
I am not using LSPosed or Hide My AppList. It could detect Xposed modules or something

**Comment by diedbug2002** [comment]
> I am not using LSPosed or Hide My AppList. It could detect Xposed modules or something

i am clean flash only stock app and this app no extra mod

![image](https://user-images.githubusercontent.com/25360103/197328021-d395fb5e-a16e-48af-970d-6a6146d3c9e9.png)

**Comment by diedbug2002** [comment]
Hi HuskyDG

please check this app as well
https://play.google.com/store/apps/details?id=com.esunbank.ESUNWALLET

it can detect root (crash) after this update

zygote is newly added in this version, but i already enable hide in magiskhide list

dont know if you can run this app normally

**Comment by frknkrc44** [comment]
@diedbug2002 it works with MagiskHide + Hide My Applist (also Zygisk is disabled)
But it warns about USB Debugging, don't forget to disable developer options

**Comment by diedbug2002** [comment]
> @diedbug2002 it works with MagiskHide + Hide My Applist (also Zygisk is disabled) But it warns about USB Debugging, don't forget to disable developer options

thx @frknkrc44 

is your app ver 5.0.0 ?

i am using riru and hide usb debug form HuskyDG with HMA but still no luck

**Comment by zongh4n** [comment]
> > @diedbug2002 it works with MagiskHide + Hide My Applist (also Zygisk is disabled) But it warns about USB Debugging, don't forget to disable developer options
> 
> thx @frknkrc44
> 
> is your app ver 5.0.0 ?
> 
> i am using riru and hide usb debug form HuskyDG with HMA but still no luck

update your riru core and momohider. it's work for me

**Comment by diedbug2002** [comment]
thanks all for helping 

I will keep investigate what's wrong of my device
