### ISSUE TITLE
Magisk Delta prevents Google Chrome to work properly

### ISSUE THREAD

**Issue by sn-o-w** [HuskyDG/magisk-files#36]
I open Chrome and after a few secs, the app automatically closes.

Not sure if this problem is related to the official Magisk, but I didn't see any similar issue reported on topjohnwu's repo.

I tested with the unmodified boot.img and the Chrome app works as expected.

I have attached some logs, hope they are useful.

[nexus5-logs.zip](https://github.com/HuskyDG/magisk-files/files/10016961/nexus5-logs.zip)
[magisk_log_2022-11-16T01.50.42.log](https://github.com/HuskyDG/magisk-files/files/10016962/magisk_log_2022-11-16T01.50.42.log)

**Comment by HuskyDG** [comment]
Please do not use momohider ans unshare at same time
```
04-22 12:17:21.227   221   223 I : riru_momohider: exec [service.sh]
11-16 01:44:54.005   221   223 I : riru-unshare: exec [service.sh]
```
