### ISSUE TITLE
Persist partition being used for early-mount.d

### ISSUE THREAD

**Issue by Namelesswonder** [HuskyDG/magisk-files#37]
Tampering with the persist partition is not a good idea in general, but for devices with a backup persist partition this concern is somewhat mitigated.  
However, I would say the majority of devices do not have a backup persist, and that mounting persist and allowing modules to use it for early-mount.d has a couple concerning issues.

1. Possibility of causing corruption by allowing it to be filled or mistreated
2. Any files put on to persist are going to survive wipes or factory resets

For the first issue it would be best to add to the documentation that module developers should check the available space on the early-mount mount if they are planning on adding multiple megabyte files so as to not fill it up if persist/metadata/cache are the backer for it. Something like `df $(magisk --path)/.magisk/mirror/early-mount | tail -n 1 | sed 's/ \{1,\}/\t/g' | cut -f 4` in their installer script would allow them to get the space available in kilobytes. This will work with both the built-in ash and system toybox.  
Module uninstall scripts shouldn't have any problems if they aren't made terribly.

For the second issue there should be a warning in the Magisk logs that the persist partition is being used and in the documentation that if the persist partition is being used for early-mount.d then to manually remove the folder or uninstall modules before factory resetting. If forgotten about or because of bad files then stock Magisk can be used to remove the folder.

Finally a notice that devices that can only use persist for early-mount.d should backup their persist before installing Magisk Delta by using `dd if=/dev/block/by-name/persist of=/sdcard/persist.img`. That would help prevent anyone from losing their factory calibration due to corruption/negligence.

For devices, the only one I have checked with is the Pixel 7 Pro, which has it's persist partition used. Given the similarities with the Pixel 6 line, they too should have their persist partition used. It's a decent chance that earlier Pixels also are the same.

As for removing persist from being used, I don't think that is necessary. I'm finding use in the fact that it isn't touched by a factory reset, but users should be told so they don't irreversibly damage their devices.

**Comment by HuskyDG** [comment]
Do you have another ext4 partition that can be mounted in magiskinit stage?

**Comment by Namelesswonder** [comment]
> Do you have another ext4 partition that can be mounted in magiskinit stage?

As far as I know, no. Magisk tests and skips over using /data/unencrypted, /data/adb, /data/cache, and metadata during mount_rules_dir().
We don't have many good partitions that aren't checked by AVB but are wiped by a factory reset.
With /data probably not working because of encryption and MagiskInit not wanting to touch metadata there is nothing to do other than use persist.

**Comment by HuskyDG** [comment]
I added reminder when Magisk Delta is using `/persist` as `early-mount.d`
Afaik there are only modules from [reiryuki](https://github.com/reiryuki) which use the `early-mount.d` for mounting `manifest.xml` for `hwservicemanager` which start earlier than Magisk and it is trouble to restart `hwservicemanager`.
