### ISSUE TITLE
Riru and LSPosed doesn't work anymore?!

### ISSUE THREAD

**Issue by sn-o-w** [HuskyDG/magisk-files#38]
Hi there,

For some reason, Riru and LSPosed don't work anymore.

This time I disabled both momohider and unshare, but no use.

[magisk_log_2022-11-19T14.46.02.log](https://github.com/HuskyDG/magisk-files/files/10047009/magisk_log_2022-11-19T14.46.02.log)

Another weird thing is that if I remove Magisk modules, then reboot the device, after rebooting inside Magisk Delta I still see those Magisk Modules in the "will delete after restart" state, those modules don't disappear. 😕

Most likely this/these happen(s) due to your latest changes.

**Comment by sn-o-w** [comment]
In magisk log there are two lines:
`E : write failed with 5: I/O error`
`E : write failed with 5: I/O error`

If Magisk log isn't enough: [2022-11-19_15.03.zip](https://github.com/HuskyDG/magisk-files/files/10047042/2022-11-19_15.03.zip)

**Comment by HuskyDG** [comment]
```
04-25 23:09:28.149   219   221 I : ** Core-only mode, skip loading modules
```

**Comment by sn-o-w** [comment]
What? I swear I didn't touch settings at all. How core-only mode got enabled?

**Comment by sn-o-w** [comment]
After disabling core-only mode now the device bootloops... Trying to obtain logs...

**Comment by sn-o-w** [comment]
After another restart, device didn't bootloop anymore... Okaaaay....
