### ISSUE TITLE
Pixel 7 support? 

### ISSUE THREAD

**Issue by Jon8RFC** [HuskyDG/magisk-files#39]
Sorry to make an issue for these questions, but I would rather not experiment to get the answers.

Is this compatible with pixel 7, being 64-bit only?
Can the bootloop protection be permanently disabled (and never inadvertently/accidentally enabled), prior to installation/reboot?

**Comment by HuskyDG** [comment]
> Is this compatible with pixel 7, being 64-bit only? 

Yes
> Can the bootloop protection be permanently disabled (and never inadvertently/accidentally enabled), prior to installation/reboot?

Yes, and it will not accidentally enabled

**Comment by Jon8RFC** [comment]
Great, thanks!
