### ISSUE TITLE
su detected by following code 

### ISSUE THREAD

**Issue by Hifi-Games-Pro** [HuskyDG/magisk-files#4]
Hello sir, 
your magisk works now on LDPlayer Android 9 and you are great. Please don't stop future updates because  Magisk Delta only provides the way to install without a boot image. sir one simple issue is one app has a below code that detects root. I already added an app on magisk hide, but not work.

Code is:- 

private static boolean searchPathForBinary(String binary) {
   String[] paths = System.getenv("PATH").split(":");
   for(String path : paths) {
      File pathDir = new File(path);
      if(pathDir.exists() && pathDir.isDirectory()) {
         File[] pathDirFiles = pathDir.listFiles();
         if(pathDirFiles != null) {
            for (File fileInPath : pathDirFiles) {
               if (fileInPath.getName().equals(binary)) {
                  return true;
               }
            }
         }
      }
   }
   return false;
}
public static boolean isRooted() {
   try {
      return searchPathForBinary("su");
   } catch(Exception e) {
      DeviceLog.exception("Rooted check failed", e);
      return false;
   } 
}

**Comment by HuskyDG** [comment]
Turn off built-in root

**Comment by HuskyDG** [comment]
Btw, Hiding root is meanless because of SELinux Permissive

**Comment by Hifi-Games-Pro** [comment]
already turned off in LDPlayer. but not work.

**Comment by Hifi-Games-Pro** [comment]
without installing magisk if I turned off the root so that is not detected as a root. but with magisk built-in root disabled, also detect as a root. can problem in magisk hide?

**Comment by HuskyDG** [comment]
> without installing magisk if I turned off the root so that is not detected as a root. but with magisk built-in root disabled, also detect as a root. can problem in magisk hide?

Show me Magisk debug logs

**Comment by Hifi-Games-Pro** [comment]
---Magisk Logs---
25.1-delta-2 (25100)

07-27 19:45:17.552  6750  6750 I : zygisk64: [com.hifi.game2048] is on the hidelist
07-27 19:46:21.437  7652  7652 I : zygisk64: [io.github.vvb2060.magiskdetector] is on the hidelist
07-27 19:46:21.642  7669  7669 I : zygisk64: [io.github.vvb2060.magiskdetector] is on the hidelist

**Comment by HuskyDG** [comment]
Send log from Magisk Debug

**Comment by Hifi-Games-Pro** [comment]
[magisk_log_2022-07-27T19.47.00.log](https://github.com/HuskyDG/magisk-files/files/9199526/magisk_log_2022-07-27T19.47.00.log)

**Comment by HuskyDG** [comment]
You should turn off Zygisk and send logs from Magisk Debug build. I do't accept logs from Magisk Stable
