### ISSUE TITLE
On memu emulator,zygisk doesn't work when it have enabled.  -- Issues connection

### ISSUE THREAD

**Issue by huayuprophet** [HuskyDG/magisk-files#5]
_I'm sorry it took a long time to reply. This is caused by jet lag and busy work_

There is logs on stable release. Zygisk is failed when enabled.
[magisk_log_2022-07-28T06.10.08.log](https://github.com/HuskyDG/magisk-files/files/9199786/magisk_log_2022-07-28T06.10.08.log)
![图片](https://user-images.githubusercontent.com/106079510/181272213-e263d762-45da-40c8-8eb1-1c5f07b9cc94.png)

There is logs on DEBUG release. Zygisk is successful.
[magisk_log_2022-07-27T22.18.26.log](https://github.com/HuskyDG/magisk-files/files/9199861/magisk_log_2022-07-27T22.18.26.log)

Reference: https://github.com/HuskyDG/magisk-files/issues/3

**Comment by HuskyDG** [comment]
Actually I have no idea how to fix it, please use another emulator
