### ISSUE TITLE
How to use Adaway with Kitsune 26404+? 

### ISSUE THREAD

**Issue by xyzabczyx** [HuskyDG/magisk-files#58]
Is there any possibility to use the Adaway app with the latest Kitsune version? 

Comments of the Kitsune 26404+ version:

"Cancel the writable exception for /system/etc/hosts. Please write to safely place /data/adb/modules/hosts/system/etc/hosts (built-in hosts) instead. App like Adaway might not work (the fact this app has not been updated for long)"

**Comment by xlukas1337** [comment]
AdAway is working fine for me on latest Kitsune

**Comment by xyzabczyx** [comment]
AdAway is also working fine for me on latest Kitsune. I learnt from XDA that the Systemless Hosts module need to be activated in Kitsune/Magisk.
