### ISSUE TITLE
Install at LDPlayer9 fail

### ISSUE THREAD

**Issue by MAYBreath** [HuskyDG/magisk-files#6]
![33322](https://user-images.githubusercontent.com/9080733/181294120-106881f4-0c49-4fab-9bc3-2be75674a921.png)

LDPlayer has been release a new andorid 9 version emulator，delta  cannot install properly.

**Comment by HuskyDG** [comment]
Already fixed in Canary

**Comment by MAYBreath** [comment]
> Already fixed in Canary

thanks，great job.
