### ISSUE TITLE
Correct information about Logo 

### ISSUE THREAD

**Issue by VisionR1** [HuskyDG/magisk-files#63]
@HuskyDG I modification again your logo, same icon with my previous and same fonts, i chance it like this because in xda lot of user confused about the the name because the logo and in the README.md still say Magisk Delta in the logo
![IMG_20240108_154114](https://github.com/HuskyDG/magisk-files/assets/25982450/ab557c83-7fb1-415f-a413-bfed459d2792)

Here my suggestion, if you want something different just tell me
![sketch-1704720503396](https://github.com/HuskyDG/magisk-files/assets/25982450/d430c734-5237-4bd2-b53a-3b03932d337c)
![sketch-1704720506837](https://github.com/HuskyDG/magisk-files/assets/25982450/b8a011dd-7663-4263-a945-8c1d2455555c)

**Comment by agret** [comment]
Magisk Delta is the name of the project isn't it? Kitsune Mask is just the "stealth" rename of Magisk Manager app on your phone.

**Comment by VisionR1** [comment]
> Magisk Delta is the name of the project isn't it? Kitsune Mask is just the "stealth" rename of Magisk Manager app on your phone.

I think not, now is Kitsune Mask, and without "Stealth" still Kitsune Mask
