### ISSUE TITLE
Direct install not working in the latest magisk delta debug builds

### ISSUE THREAD

**Issue by martyfender** [HuskyDG/magisk-files#8]
Direct install not working in the latest 2 magisk delta debug builds, nor trying to install the renamed zip file in the modules section. I ended up having to flash the zip in twrp. I have never experienced this in the past with delta debug builds. These are the new builds with the OneUI. The magisk app just closes when trying the direct install.
Magisk 384a95b4-delta
Magisk 38fc1599-delta
Onn 8 1st gen, Android 9

Thanks

**Comment by martyfender** [comment]
[Log_2022-07-31_08-38-04.txt](https://github.com/HuskyDG/magisk-files/files/9228867/Log_2022-07-31_08-38-04.txt)

**Comment by HuskyDG** [comment]
I will revert to use default, thanks

**Comment by HuskyDG** [comment]
But the log does not contain anything useful, please record it before crashing

**Comment by martyfender** [comment]
[Uploading Log_2022-07-31_08-38-04.txt…]()
[Log_2022-07-31_09-01-28.txt](https://github.com/HuskyDG/magisk-files/files/9228902/Log_2022-07-31_09-01-28.txt)

**Comment by HuskyDG** [comment]
You can press save button in Logs

**Comment by martyfender** [comment]
These were per app logcats filtered for the hidden magisk app in logcat extreme. I you need full logcats, I won't be able to provide them until much later, after work. I did save them in the app.
Thanks

**Comment by martyfender** [comment]
This is fixed with the new release, f3a24d75

Thanks
