### ISSUE TITLE
Canary and Debug don't work together with MagiskOnWSA

### ISSUE THREAD

**Issue by conloi** [HuskyDG/magisk-files#9]
Hi there,

Canary and debug versions don't work with [MagiskOnWSA](https://github.com/LSPosed/MagiskOnWSA/).

Beta version seems to work, perhaps Stable too (never tested Stable tho, but most likely if is very similar to Beta, it should work I guess)

Have you made some bigger changes to Canary/Debug compared to Stable/Beta? 🤔

**Comment by HuskyDG** [comment]
Test the latest canary, i might have fixed it

**Comment by conloi** [comment]
@HuskyDG I can confirm Canary works now with MagiskOnWSA. 👍

**Comment by HuskyDG** [comment]
It's recommended to refer to this https://huskydg.github.io/magisk-files/#how-to-install-magisk-into-wsa
