### ISSUE TITLE
Unable to root Pixel 7 Pro

### ISSUE THREAD

**Issue by ZerkerEOD** [HuskyDG/magisk-files#94]
Maybe the developer could add some additional context through comments of why it's not planned? I've tried several methods including the official methods included in the readme. When you mark the issue preventing others from commenting on a legitimate issue without a valid explanation is going to cause confusion with others that may have the same issue.

Issue in response to issue https://github.com/HuskyDG/magisk-files/issues/93#issue-2092502452

**Comment by sawdoctor** [comment]
I noticed you are on pixel 8 pro. There was a similar issue with the pixel fold on QPR2 beta with latest magisk canary, root could not be obtained. The issue was corrected when QPR 2 beta 3 was released, it might be the same/similar issue

**Comment by ZerkerEOD** [comment]
@sawdoctor thanks, I actually finally figured it out. I had to flash an unrooted init_boot and then reboot then flash the patched ones again. No clue why but I got root restored that way. How it can help someone else.

**Comment by andrevmatos** [comment]
I'm getting the same issue on latest canary build on latest GrapheneOS (20240205). While on default init_boot.img, I can install and open the Magisk Delta app, patch the init_boot.img, reboot and flash it; then, after rebooting, Magisk app uninstalls itself everytime I try to open it.
